/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ConsoleV1TagsControllerGenListStatus = {
    FourHundredAndFour: 404,
} as const;
export type ConsoleV1TagsControllerGenListStatus = ClosedEnum<
    typeof ConsoleV1TagsControllerGenListStatus
>;

/**
 * Tag not found. The requested resource could not be found.
 */
export type ConsoleV1TagsControllerGenListResponseBodyData = {
    status: ConsoleV1TagsControllerGenListStatus;
    message: string;
};

/**
 * Tag not found. The requested resource could not be found.
 */
export class ConsoleV1TagsControllerGenListResponseBody extends Error {
    status: ConsoleV1TagsControllerGenListStatus;

    /** The original data that was passed to this error instance. */
    data$: ConsoleV1TagsControllerGenListResponseBodyData;

    constructor(err: ConsoleV1TagsControllerGenListResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.status = err.status;

        this.name = "ConsoleV1TagsControllerGenListResponseBody";
    }
}

/** @internal */
export const ConsoleV1TagsControllerGenListStatus$inboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1TagsControllerGenListStatus
> = z.nativeEnum(ConsoleV1TagsControllerGenListStatus);

/** @internal */
export const ConsoleV1TagsControllerGenListStatus$outboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1TagsControllerGenListStatus
> = ConsoleV1TagsControllerGenListStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1TagsControllerGenListStatus$ {
    /** @deprecated use `ConsoleV1TagsControllerGenListStatus$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1TagsControllerGenListStatus$inboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenListStatus$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1TagsControllerGenListStatus$outboundSchema;
}

/** @internal */
export const ConsoleV1TagsControllerGenListResponseBody$inboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenListResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        status: ConsoleV1TagsControllerGenListStatus$inboundSchema,
        message: z.string(),
    })
    .transform((v) => {
        return new ConsoleV1TagsControllerGenListResponseBody(v);
    });

/** @internal */
export type ConsoleV1TagsControllerGenListResponseBody$Outbound = {
    status: number;
    message: string;
};

/** @internal */
export const ConsoleV1TagsControllerGenListResponseBody$outboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenListResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1TagsControllerGenListResponseBody
> = z
    .instanceof(ConsoleV1TagsControllerGenListResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            status: ConsoleV1TagsControllerGenListStatus$outboundSchema,
            message: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1TagsControllerGenListResponseBody$ {
    /** @deprecated use `ConsoleV1TagsControllerGenListResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1TagsControllerGenListResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenListResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1TagsControllerGenListResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenListResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1TagsControllerGenListResponseBody$Outbound;
}
