/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ConsoleV1LayersControllerGenCreateLayersStatus = {
    FourHundredAndOne: 401,
} as const;
export type ConsoleV1LayersControllerGenCreateLayersStatus = ClosedEnum<
    typeof ConsoleV1LayersControllerGenCreateLayersStatus
>;

/**
 * This endpoint only accepts an active CONSOLE key, but an invalid key was sent. Key: console-xxxXXXxxxXXXxxx
 */
export type ConsoleV1LayersControllerGenCreateLayersResponseBodyData = {
    status: ConsoleV1LayersControllerGenCreateLayersStatus;
    message: string;
};

/**
 * This endpoint only accepts an active CONSOLE key, but an invalid key was sent. Key: console-xxxXXXxxxXXXxxx
 */
export class ConsoleV1LayersControllerGenCreateLayersResponseBody extends Error {
    status: ConsoleV1LayersControllerGenCreateLayersStatus;

    /** The original data that was passed to this error instance. */
    data$: ConsoleV1LayersControllerGenCreateLayersResponseBodyData;

    constructor(err: ConsoleV1LayersControllerGenCreateLayersResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.status = err.status;

        this.name = "ConsoleV1LayersControllerGenCreateLayersResponseBody";
    }
}

export const ConsoleV1LayersControllerGenCreateStatus = {
    FourHundred: 400,
} as const;
export type ConsoleV1LayersControllerGenCreateStatus = ClosedEnum<
    typeof ConsoleV1LayersControllerGenCreateStatus
>;

/**
 * Invalid request. Please check the request input and try again.
 */
export type ConsoleV1LayersControllerGenCreateResponseBodyData = {
    status: ConsoleV1LayersControllerGenCreateStatus;
    message: string;
};

/**
 * Invalid request. Please check the request input and try again.
 */
export class ConsoleV1LayersControllerGenCreateResponseBody extends Error {
    status: ConsoleV1LayersControllerGenCreateStatus;

    /** The original data that was passed to this error instance. */
    data$: ConsoleV1LayersControllerGenCreateResponseBodyData;

    constructor(err: ConsoleV1LayersControllerGenCreateResponseBodyData) {
        const message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : `API error occurred: ${JSON.stringify(err)}`;
        super(message);
        this.data$ = err;

        this.status = err.status;

        this.name = "ConsoleV1LayersControllerGenCreateResponseBody";
    }
}

/** @internal */
export const ConsoleV1LayersControllerGenCreateLayersStatus$inboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1LayersControllerGenCreateLayersStatus
> = z.nativeEnum(ConsoleV1LayersControllerGenCreateLayersStatus);

/** @internal */
export const ConsoleV1LayersControllerGenCreateLayersStatus$outboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1LayersControllerGenCreateLayersStatus
> = ConsoleV1LayersControllerGenCreateLayersStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenCreateLayersStatus$ {
    /** @deprecated use `ConsoleV1LayersControllerGenCreateLayersStatus$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenCreateLayersStatus$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateLayersStatus$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1LayersControllerGenCreateLayersStatus$outboundSchema;
}

/** @internal */
export const ConsoleV1LayersControllerGenCreateLayersResponseBody$inboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenCreateLayersResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        status: ConsoleV1LayersControllerGenCreateLayersStatus$inboundSchema,
        message: z.string(),
    })
    .transform((v) => {
        return new ConsoleV1LayersControllerGenCreateLayersResponseBody(v);
    });

/** @internal */
export type ConsoleV1LayersControllerGenCreateLayersResponseBody$Outbound = {
    status: number;
    message: string;
};

/** @internal */
export const ConsoleV1LayersControllerGenCreateLayersResponseBody$outboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenCreateLayersResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1LayersControllerGenCreateLayersResponseBody
> = z
    .instanceof(ConsoleV1LayersControllerGenCreateLayersResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            status: ConsoleV1LayersControllerGenCreateLayersStatus$outboundSchema,
            message: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenCreateLayersResponseBody$ {
    /** @deprecated use `ConsoleV1LayersControllerGenCreateLayersResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenCreateLayersResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateLayersResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1LayersControllerGenCreateLayersResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateLayersResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1LayersControllerGenCreateLayersResponseBody$Outbound;
}

/** @internal */
export const ConsoleV1LayersControllerGenCreateStatus$inboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1LayersControllerGenCreateStatus
> = z.nativeEnum(ConsoleV1LayersControllerGenCreateStatus);

/** @internal */
export const ConsoleV1LayersControllerGenCreateStatus$outboundSchema: z.ZodNativeEnum<
    typeof ConsoleV1LayersControllerGenCreateStatus
> = ConsoleV1LayersControllerGenCreateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenCreateStatus$ {
    /** @deprecated use `ConsoleV1LayersControllerGenCreateStatus$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenCreateStatus$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateStatus$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1LayersControllerGenCreateStatus$outboundSchema;
}

/** @internal */
export const ConsoleV1LayersControllerGenCreateResponseBody$inboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenCreateResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        status: ConsoleV1LayersControllerGenCreateStatus$inboundSchema,
        message: z.string(),
    })
    .transform((v) => {
        return new ConsoleV1LayersControllerGenCreateResponseBody(v);
    });

/** @internal */
export type ConsoleV1LayersControllerGenCreateResponseBody$Outbound = {
    status: number;
    message: string;
};

/** @internal */
export const ConsoleV1LayersControllerGenCreateResponseBody$outboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenCreateResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1LayersControllerGenCreateResponseBody
> = z
    .instanceof(ConsoleV1LayersControllerGenCreateResponseBody)
    .transform((v) => v.data$)
    .pipe(
        z.object({
            status: ConsoleV1LayersControllerGenCreateStatus$outboundSchema,
            message: z.string(),
        })
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenCreateResponseBody$ {
    /** @deprecated use `ConsoleV1LayersControllerGenCreateResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenCreateResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1LayersControllerGenCreateResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenCreateResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1LayersControllerGenCreateResponseBody$Outbound;
}
