/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { experimentsWarehouseNativeCreateAssignmentSource } from "../funcs/experimentsWarehouseNativeCreateAssignmentSource.js";
import { experimentsWarehouseNativeCreateEntityPropertySource } from "../funcs/experimentsWarehouseNativeCreateEntityPropertySource.js";
import { experimentsWarehouseNativeListAssignmentSources } from "../funcs/experimentsWarehouseNativeListAssignmentSources.js";
import { experimentsWarehouseNativeListEntityPropertySources } from "../funcs/experimentsWarehouseNativeListEntityPropertySources.js";
import { experimentsWarehouseNativeLoadPulse } from "../funcs/experimentsWarehouseNativeLoadPulse.js";
import { experimentsWarehouseNativePulseLoadHistory } from "../funcs/experimentsWarehouseNativePulseLoadHistory.js";
import { experimentsWarehouseNativeRemoveEntityPropertySource } from "../funcs/experimentsWarehouseNativeRemoveEntityPropertySource.js";
import { experimentsWarehouseNativeUpdateAssignmentSource } from "../funcs/experimentsWarehouseNativeUpdateAssignmentSource.js";
import { experimentsWarehouseNativeUpdateEntityPropertySource } from "../funcs/experimentsWarehouseNativeUpdateEntityPropertySource.js";
import { experimentsWarehouseNativeUpdateEntityPropertySourceQuery } from "../funcs/experimentsWarehouseNativeUpdateEntityPropertySourceQuery.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ExperimentsWarehouseNative extends ClientSDK {
    /**
     * Load Pulse (Warehouse Native)
     */
    async loadPulse(
        request: operations.ConsoleV1ExperimentsControllerGenLoadPulseRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenLoadPulseResponseBody> {
        return unwrapAsync(experimentsWarehouseNativeLoadPulse(this, request, options));
    }

    /**
     * Pulse Load History (Warehouse Native)
     */
    async pulseLoadHistory(
        request: operations.ConsoleV1ExperimentsControllerGenPulseLoadHistoryRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenPulseLoadHistoryResponseBody> {
        return unwrapAsync(experimentsWarehouseNativePulseLoadHistory(this, request, options));
    }

    /**
     * Create Entity Property Source
     */
    async createEntityPropertySource(
        request: operations.ConsoleV1ExperimentsControllerGenCreateEntityPropertySourceRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenCreateEntityPropertySourceResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeCreateEntityPropertySource(this, request, options)
        );
    }

    /**
     * List Entity Property Sources
     */
    async listEntityPropertySources(
        request: operations.ConsoleV1ExperimentsControllerGenListEntityPropertySourcesRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenListEntityPropertySourcesResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeListEntityPropertySources(this, request, options)
        );
    }

    /**
     * Patch Entity Property Source
     */
    async updateEntityPropertySource(
        request: operations.ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeUpdateEntityPropertySource(this, request, options)
        );
    }

    /**
     * Post Entity Property Source
     */
    async updateEntityPropertySourceQuery(
        request: operations.ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeUpdateEntityPropertySourceQuery(this, request, options)
        );
    }

    /**
     * Delete Entity Property Source
     */
    async removeEntityPropertySource(
        request: operations.ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeRemoveEntityPropertySource(this, request, options)
        );
    }

    /**
     * Create Assignment Source
     */
    async createAssignmentSource(
        request: operations.ConsoleV1ExperimentsControllerGenCreateAssignmentSourceRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenCreateAssignmentSourceResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeCreateAssignmentSource(this, request, options)
        );
    }

    /**
     * List Assignment Sources
     */
    async listAssignmentSources(
        request: operations.ConsoleV1ExperimentsControllerGenListAssignmentSourcesRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenListAssignmentSourcesResponseBody> {
        return unwrapAsync(experimentsWarehouseNativeListAssignmentSources(this, request, options));
    }

    /**
     * Patch Assignment Source
     */
    async updateAssignmentSource(
        request: operations.ConsoleV1ExperimentsControllerGenUpdateAssignmentSourceRequest,
        options?: RequestOptions
    ): Promise<operations.ConsoleV1ExperimentsControllerGenUpdateAssignmentSourceResponseBody> {
        return unwrapAsync(
            experimentsWarehouseNativeUpdateAssignmentSource(this, request, options)
        );
    }
}
