/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1GatesControllerGenMultiRuleUpdateRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    multiRuleUpdateDto: components.MultiRuleUpdateDto;
};

/**
 * Update gate response
 */
export type ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.ExternalGateDto;
};

/** @internal */
export const ConsoleV1GatesControllerGenMultiRuleUpdateRequest$inboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenMultiRuleUpdateRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        MultiRuleUpdateDto: components.MultiRuleUpdateDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            MultiRuleUpdateDto: "multiRuleUpdateDto",
        });
    });

/** @internal */
export type ConsoleV1GatesControllerGenMultiRuleUpdateRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    MultiRuleUpdateDto: components.MultiRuleUpdateDto$Outbound;
};

/** @internal */
export const ConsoleV1GatesControllerGenMultiRuleUpdateRequest$outboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenMultiRuleUpdateRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1GatesControllerGenMultiRuleUpdateRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        multiRuleUpdateDto: components.MultiRuleUpdateDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            multiRuleUpdateDto: "MultiRuleUpdateDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GatesControllerGenMultiRuleUpdateRequest$ {
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1GatesControllerGenMultiRuleUpdateRequest$inboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1GatesControllerGenMultiRuleUpdateRequest$outboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateRequest$Outbound` instead. */
    export type Outbound = ConsoleV1GatesControllerGenMultiRuleUpdateRequest$Outbound;
}

/** @internal */
export const ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$inboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.ExternalGateDto$inboundSchema,
});

/** @internal */
export type ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$Outbound = {
    message: string;
    data: components.ExternalGateDto$Outbound;
};

/** @internal */
export const ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$outboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody
> = z.object({
    message: z.string(),
    data: components.ExternalGateDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$ {
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1GatesControllerGenMultiRuleUpdateResponseBody$Outbound;
}
