/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1DynamicConfigControllerGenRuleAddRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    dynamicConfigRuleAddDto: components.DynamicConfigRuleAddDto;
};

/**
 * Add Dynamic Config Rule Response
 */
export type ConsoleV1DynamicConfigControllerGenRuleAddResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.DynamicConfigDto;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenRuleAddRequest$inboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenRuleAddRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        DynamicConfigRuleAddDto: components.DynamicConfigRuleAddDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            DynamicConfigRuleAddDto: "dynamicConfigRuleAddDto",
        });
    });

/** @internal */
export type ConsoleV1DynamicConfigControllerGenRuleAddRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    DynamicConfigRuleAddDto: components.DynamicConfigRuleAddDto$Outbound;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenRuleAddRequest$outboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenRuleAddRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1DynamicConfigControllerGenRuleAddRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        dynamicConfigRuleAddDto: components.DynamicConfigRuleAddDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            dynamicConfigRuleAddDto: "DynamicConfigRuleAddDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1DynamicConfigControllerGenRuleAddRequest$ {
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1DynamicConfigControllerGenRuleAddRequest$inboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1DynamicConfigControllerGenRuleAddRequest$outboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddRequest$Outbound` instead. */
    export type Outbound = ConsoleV1DynamicConfigControllerGenRuleAddRequest$Outbound;
}

/** @internal */
export const ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$inboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenRuleAddResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.DynamicConfigDto$inboundSchema,
});

/** @internal */
export type ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$Outbound = {
    message: string;
    data: components.DynamicConfigDto$Outbound;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$outboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1DynamicConfigControllerGenRuleAddResponseBody
> = z.object({
    message: z.string(),
    data: components.DynamicConfigDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$ {
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1DynamicConfigControllerGenRuleAddResponseBody$Outbound;
}
