/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1IngestionControllerGenCreateIngestionSourceRequest = {
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    ingestionSourceCreateContractDto: components.IngestionSourceCreateContractDto;
};

/**
 * Create Ingestion Success
 */
export type ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.IngestionDto;
};

/** @internal */
export const ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$inboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenCreateIngestionSourceRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-respect-review-settings": z.string().optional(),
        IngestionSourceCreateContractDto: components.IngestionSourceCreateContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            IngestionSourceCreateContractDto: "ingestionSourceCreateContractDto",
        });
    });

/** @internal */
export type ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$Outbound = {
    "x-respect-review-settings"?: string | undefined;
    IngestionSourceCreateContractDto: components.IngestionSourceCreateContractDto$Outbound;
};

/** @internal */
export const ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$outboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1IngestionControllerGenCreateIngestionSourceRequest
> = z
    .object({
        xRespectReviewSettings: z.string().optional(),
        ingestionSourceCreateContractDto:
            components.IngestionSourceCreateContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            ingestionSourceCreateContractDto: "IngestionSourceCreateContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$ {
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$inboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$outboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$Outbound` instead. */
    export type Outbound = ConsoleV1IngestionControllerGenCreateIngestionSourceRequest$Outbound;
}

/** @internal */
export const ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$inboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.IngestionDto$inboundSchema,
});

/** @internal */
export type ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$Outbound = {
    message: string;
    data: components.IngestionDto$Outbound;
};

/** @internal */
export const ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$outboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody
> = z.object({
    message: z.string(),
    data: components.IngestionDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$ {
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$Outbound` instead. */
    export type Outbound =
        ConsoleV1IngestionControllerGenCreateIngestionSourceResponseBody$Outbound;
}
