/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1SegmentsIDListControllerAddRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    segmentIDListContractDto: components.SegmentIDListContractDto;
};

/**
 * Segment ids updated successfully.
 */
export type ConsoleV1SegmentsIDListControllerAddResponseBody = {
    message?: string | undefined;
};

/** @internal */
export const ConsoleV1SegmentsIDListControllerAddRequest$inboundSchema: z.ZodType<
    ConsoleV1SegmentsIDListControllerAddRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        SegmentIDListContractDto: components.SegmentIDListContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            SegmentIDListContractDto: "segmentIDListContractDto",
        });
    });

/** @internal */
export type ConsoleV1SegmentsIDListControllerAddRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    SegmentIDListContractDto: components.SegmentIDListContractDto$Outbound;
};

/** @internal */
export const ConsoleV1SegmentsIDListControllerAddRequest$outboundSchema: z.ZodType<
    ConsoleV1SegmentsIDListControllerAddRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1SegmentsIDListControllerAddRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        segmentIDListContractDto: components.SegmentIDListContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            segmentIDListContractDto: "SegmentIDListContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1SegmentsIDListControllerAddRequest$ {
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1SegmentsIDListControllerAddRequest$inboundSchema;
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1SegmentsIDListControllerAddRequest$outboundSchema;
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddRequest$Outbound` instead. */
    export type Outbound = ConsoleV1SegmentsIDListControllerAddRequest$Outbound;
}

/** @internal */
export const ConsoleV1SegmentsIDListControllerAddResponseBody$inboundSchema: z.ZodType<
    ConsoleV1SegmentsIDListControllerAddResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
});

/** @internal */
export type ConsoleV1SegmentsIDListControllerAddResponseBody$Outbound = {
    message?: string | undefined;
};

/** @internal */
export const ConsoleV1SegmentsIDListControllerAddResponseBody$outboundSchema: z.ZodType<
    ConsoleV1SegmentsIDListControllerAddResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1SegmentsIDListControllerAddResponseBody
> = z.object({
    message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1SegmentsIDListControllerAddResponseBody$ {
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1SegmentsIDListControllerAddResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1SegmentsIDListControllerAddResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1SegmentsIDListControllerAddResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1SegmentsIDListControllerAddResponseBody$Outbound;
}
