/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1ExperimentOverridesControllerGenReadRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Get Experiment Overrides Success
 */
export type ConsoleV1ExperimentOverridesControllerGenReadResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.ExperimentOverridesDto;
};

/** @internal */
export const ConsoleV1ExperimentOverridesControllerGenReadRequest$inboundSchema: z.ZodType<
    ConsoleV1ExperimentOverridesControllerGenReadRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1ExperimentOverridesControllerGenReadRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1ExperimentOverridesControllerGenReadRequest$outboundSchema: z.ZodType<
    ConsoleV1ExperimentOverridesControllerGenReadRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentOverridesControllerGenReadRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentOverridesControllerGenReadRequest$ {
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1ExperimentOverridesControllerGenReadRequest$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentOverridesControllerGenReadRequest$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadRequest$Outbound` instead. */
    export type Outbound = ConsoleV1ExperimentOverridesControllerGenReadRequest$Outbound;
}

/** @internal */
export const ConsoleV1ExperimentOverridesControllerGenReadResponseBody$inboundSchema: z.ZodType<
    ConsoleV1ExperimentOverridesControllerGenReadResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.ExperimentOverridesDto$inboundSchema,
});

/** @internal */
export type ConsoleV1ExperimentOverridesControllerGenReadResponseBody$Outbound = {
    message: string;
    data: components.ExperimentOverridesDto$Outbound;
};

/** @internal */
export const ConsoleV1ExperimentOverridesControllerGenReadResponseBody$outboundSchema: z.ZodType<
    ConsoleV1ExperimentOverridesControllerGenReadResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentOverridesControllerGenReadResponseBody
> = z.object({
    message: z.string(),
    data: components.ExperimentOverridesDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentOverridesControllerGenReadResponseBody$ {
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1ExperimentOverridesControllerGenReadResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentOverridesControllerGenReadResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentOverridesControllerGenReadResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1ExperimentOverridesControllerGenReadResponseBody$Outbound;
}
