/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1EventsControllerGenListRequest = {
    /**
     * Results per page
     */
    limit?: any | undefined;
    /**
     * Page number
     */
    page?: any | undefined;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * List Events response
 */
export type ConsoleV1EventsControllerGenListResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.LoggedEventDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1EventsControllerGenListRequest$inboundSchema: z.ZodType<
    ConsoleV1EventsControllerGenListRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1EventsControllerGenListRequest$Outbound = {
    limit?: any | undefined;
    page?: any | undefined;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1EventsControllerGenListRequest$outboundSchema: z.ZodType<
    ConsoleV1EventsControllerGenListRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1EventsControllerGenListRequest
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1EventsControllerGenListRequest$ {
    /** @deprecated use `ConsoleV1EventsControllerGenListRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1EventsControllerGenListRequest$inboundSchema;
    /** @deprecated use `ConsoleV1EventsControllerGenListRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1EventsControllerGenListRequest$outboundSchema;
    /** @deprecated use `ConsoleV1EventsControllerGenListRequest$Outbound` instead. */
    export type Outbound = ConsoleV1EventsControllerGenListRequest$Outbound;
}

/** @internal */
export const ConsoleV1EventsControllerGenListResponseBody$inboundSchema: z.ZodType<
    ConsoleV1EventsControllerGenListResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.LoggedEventDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1EventsControllerGenListResponseBody$Outbound = {
    message: string;
    data: Array<components.LoggedEventDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1EventsControllerGenListResponseBody$outboundSchema: z.ZodType<
    ConsoleV1EventsControllerGenListResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1EventsControllerGenListResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.LoggedEventDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1EventsControllerGenListResponseBody$ {
    /** @deprecated use `ConsoleV1EventsControllerGenListResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1EventsControllerGenListResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1EventsControllerGenListResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1EventsControllerGenListResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1EventsControllerGenListResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1EventsControllerGenListResponseBody$Outbound;
}
