/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1GateOverridesControllerGenRemoveRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Delete Gate Override Success
 */
export type ConsoleV1GateOverridesControllerGenRemoveResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    /**
     * Contract for overrides
     */
    data: components.OverrideDto;
};

/** @internal */
export const ConsoleV1GateOverridesControllerGenRemoveRequest$inboundSchema: z.ZodType<
    ConsoleV1GateOverridesControllerGenRemoveRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1GateOverridesControllerGenRemoveRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1GateOverridesControllerGenRemoveRequest$outboundSchema: z.ZodType<
    ConsoleV1GateOverridesControllerGenRemoveRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1GateOverridesControllerGenRemoveRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GateOverridesControllerGenRemoveRequest$ {
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1GateOverridesControllerGenRemoveRequest$inboundSchema;
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1GateOverridesControllerGenRemoveRequest$outboundSchema;
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveRequest$Outbound` instead. */
    export type Outbound = ConsoleV1GateOverridesControllerGenRemoveRequest$Outbound;
}

/** @internal */
export const ConsoleV1GateOverridesControllerGenRemoveResponseBody$inboundSchema: z.ZodType<
    ConsoleV1GateOverridesControllerGenRemoveResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.OverrideDto$inboundSchema,
});

/** @internal */
export type ConsoleV1GateOverridesControllerGenRemoveResponseBody$Outbound = {
    message: string;
    data: components.OverrideDto$Outbound;
};

/** @internal */
export const ConsoleV1GateOverridesControllerGenRemoveResponseBody$outboundSchema: z.ZodType<
    ConsoleV1GateOverridesControllerGenRemoveResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1GateOverridesControllerGenRemoveResponseBody
> = z.object({
    message: z.string(),
    data: components.OverrideDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GateOverridesControllerGenRemoveResponseBody$ {
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1GateOverridesControllerGenRemoveResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1GateOverridesControllerGenRemoveResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1GateOverridesControllerGenRemoveResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1GateOverridesControllerGenRemoveResponseBody$Outbound;
}
