/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1MetricsControllerGenReadMetricSourceRequest = {
    /**
     * name
     */
    name: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Read metric source response
 */
export type ConsoleV1MetricsControllerGenReadMetricSourceResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.MetricSourceContractDto;
};

/** @internal */
export const ConsoleV1MetricsControllerGenReadMetricSourceRequest$inboundSchema: z.ZodType<
    ConsoleV1MetricsControllerGenReadMetricSourceRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        name: z.string(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1MetricsControllerGenReadMetricSourceRequest$Outbound = {
    name: string;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1MetricsControllerGenReadMetricSourceRequest$outboundSchema: z.ZodType<
    ConsoleV1MetricsControllerGenReadMetricSourceRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1MetricsControllerGenReadMetricSourceRequest
> = z
    .object({
        name: z.string(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1MetricsControllerGenReadMetricSourceRequest$ {
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1MetricsControllerGenReadMetricSourceRequest$inboundSchema;
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1MetricsControllerGenReadMetricSourceRequest$outboundSchema;
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceRequest$Outbound` instead. */
    export type Outbound = ConsoleV1MetricsControllerGenReadMetricSourceRequest$Outbound;
}

/** @internal */
export const ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$inboundSchema: z.ZodType<
    ConsoleV1MetricsControllerGenReadMetricSourceResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.MetricSourceContractDto$inboundSchema,
});

/** @internal */
export type ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$Outbound = {
    message: string;
    data: components.MetricSourceContractDto$Outbound;
};

/** @internal */
export const ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$outboundSchema: z.ZodType<
    ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1MetricsControllerGenReadMetricSourceResponseBody
> = z.object({
    message: z.string(),
    data: components.MetricSourceContractDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$ {
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1MetricsControllerGenReadMetricSourceResponseBody$Outbound;
}
