/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1SegmentsControllerGenListRequest = {
    /**
     * Results per page
     */
    limit?: any | undefined;
    /**
     * Page number
     */
    page?: any | undefined;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * List Segments Success
 */
export type ConsoleV1SegmentsControllerGenListResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.SegmentDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1SegmentsControllerGenListRequest$inboundSchema: z.ZodType<
    ConsoleV1SegmentsControllerGenListRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1SegmentsControllerGenListRequest$Outbound = {
    limit?: any | undefined;
    page?: any | undefined;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1SegmentsControllerGenListRequest$outboundSchema: z.ZodType<
    ConsoleV1SegmentsControllerGenListRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1SegmentsControllerGenListRequest
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1SegmentsControllerGenListRequest$ {
    /** @deprecated use `ConsoleV1SegmentsControllerGenListRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1SegmentsControllerGenListRequest$inboundSchema;
    /** @deprecated use `ConsoleV1SegmentsControllerGenListRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1SegmentsControllerGenListRequest$outboundSchema;
    /** @deprecated use `ConsoleV1SegmentsControllerGenListRequest$Outbound` instead. */
    export type Outbound = ConsoleV1SegmentsControllerGenListRequest$Outbound;
}

/** @internal */
export const ConsoleV1SegmentsControllerGenListResponseBody$inboundSchema: z.ZodType<
    ConsoleV1SegmentsControllerGenListResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.SegmentDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1SegmentsControllerGenListResponseBody$Outbound = {
    message: string;
    data: Array<components.SegmentDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1SegmentsControllerGenListResponseBody$outboundSchema: z.ZodType<
    ConsoleV1SegmentsControllerGenListResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1SegmentsControllerGenListResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.SegmentDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1SegmentsControllerGenListResponseBody$ {
    /** @deprecated use `ConsoleV1SegmentsControllerGenListResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1SegmentsControllerGenListResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1SegmentsControllerGenListResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1SegmentsControllerGenListResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1SegmentsControllerGenListResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1SegmentsControllerGenListResponseBody$Outbound;
}
