/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1TagsControllerGenReadRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Read Tag Success
 */
export type ConsoleV1TagsControllerGenReadResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.TagDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1TagsControllerGenReadRequest$inboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenReadRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1TagsControllerGenReadRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1TagsControllerGenReadRequest$outboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenReadRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1TagsControllerGenReadRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1TagsControllerGenReadRequest$ {
    /** @deprecated use `ConsoleV1TagsControllerGenReadRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1TagsControllerGenReadRequest$inboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenReadRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1TagsControllerGenReadRequest$outboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenReadRequest$Outbound` instead. */
    export type Outbound = ConsoleV1TagsControllerGenReadRequest$Outbound;
}

/** @internal */
export const ConsoleV1TagsControllerGenReadResponseBody$inboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenReadResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.TagDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1TagsControllerGenReadResponseBody$Outbound = {
    message: string;
    data: Array<components.TagDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1TagsControllerGenReadResponseBody$outboundSchema: z.ZodType<
    ConsoleV1TagsControllerGenReadResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1TagsControllerGenReadResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.TagDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1TagsControllerGenReadResponseBody$ {
    /** @deprecated use `ConsoleV1TagsControllerGenReadResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1TagsControllerGenReadResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenReadResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1TagsControllerGenReadResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1TagsControllerGenReadResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1TagsControllerGenReadResponseBody$Outbound;
}
