/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1GatesControllerGenRuleAddRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    ruleDto: components.RuleDto;
};

/**
 * Add Gate Rule Response
 */
export type ConsoleV1GatesControllerGenRuleAddResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.ExternalGateDto;
};

/** @internal */
export const ConsoleV1GatesControllerGenRuleAddRequest$inboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenRuleAddRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        RuleDto: components.RuleDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            RuleDto: "ruleDto",
        });
    });

/** @internal */
export type ConsoleV1GatesControllerGenRuleAddRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    RuleDto: components.RuleDto$Outbound;
};

/** @internal */
export const ConsoleV1GatesControllerGenRuleAddRequest$outboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenRuleAddRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1GatesControllerGenRuleAddRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        ruleDto: components.RuleDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            ruleDto: "RuleDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GatesControllerGenRuleAddRequest$ {
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1GatesControllerGenRuleAddRequest$inboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1GatesControllerGenRuleAddRequest$outboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddRequest$Outbound` instead. */
    export type Outbound = ConsoleV1GatesControllerGenRuleAddRequest$Outbound;
}

/** @internal */
export const ConsoleV1GatesControllerGenRuleAddResponseBody$inboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenRuleAddResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.ExternalGateDto$inboundSchema,
});

/** @internal */
export type ConsoleV1GatesControllerGenRuleAddResponseBody$Outbound = {
    message: string;
    data: components.ExternalGateDto$Outbound;
};

/** @internal */
export const ConsoleV1GatesControllerGenRuleAddResponseBody$outboundSchema: z.ZodType<
    ConsoleV1GatesControllerGenRuleAddResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1GatesControllerGenRuleAddResponseBody
> = z.object({
    message: z.string(),
    data: components.ExternalGateDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1GatesControllerGenRuleAddResponseBody$ {
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1GatesControllerGenRuleAddResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1GatesControllerGenRuleAddResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1GatesControllerGenRuleAddResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1GatesControllerGenRuleAddResponseBody$Outbound;
}
