/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1LayersControllerGenFullUpdateRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    layerFullUpdateContractDto: components.LayerFullUpdateContractDto;
};

/**
 * Update layer response
 */
export type ConsoleV1LayersControllerGenFullUpdateResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.LayerContractDto;
};

/** @internal */
export const ConsoleV1LayersControllerGenFullUpdateRequest$inboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenFullUpdateRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        LayerFullUpdateContractDto: components.LayerFullUpdateContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            LayerFullUpdateContractDto: "layerFullUpdateContractDto",
        });
    });

/** @internal */
export type ConsoleV1LayersControllerGenFullUpdateRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    LayerFullUpdateContractDto: components.LayerFullUpdateContractDto$Outbound;
};

/** @internal */
export const ConsoleV1LayersControllerGenFullUpdateRequest$outboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenFullUpdateRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1LayersControllerGenFullUpdateRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        layerFullUpdateContractDto: components.LayerFullUpdateContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            layerFullUpdateContractDto: "LayerFullUpdateContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenFullUpdateRequest$ {
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenFullUpdateRequest$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1LayersControllerGenFullUpdateRequest$outboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateRequest$Outbound` instead. */
    export type Outbound = ConsoleV1LayersControllerGenFullUpdateRequest$Outbound;
}

/** @internal */
export const ConsoleV1LayersControllerGenFullUpdateResponseBody$inboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenFullUpdateResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.LayerContractDto$inboundSchema,
});

/** @internal */
export type ConsoleV1LayersControllerGenFullUpdateResponseBody$Outbound = {
    message: string;
    data: components.LayerContractDto$Outbound;
};

/** @internal */
export const ConsoleV1LayersControllerGenFullUpdateResponseBody$outboundSchema: z.ZodType<
    ConsoleV1LayersControllerGenFullUpdateResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1LayersControllerGenFullUpdateResponseBody
> = z.object({
    message: z.string(),
    data: components.LayerContractDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1LayersControllerGenFullUpdateResponseBody$ {
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1LayersControllerGenFullUpdateResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1LayersControllerGenFullUpdateResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1LayersControllerGenFullUpdateResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1LayersControllerGenFullUpdateResponseBody$Outbound;
}
