/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1UsersControllerGenCreateTeamRequest = {
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    teamCreationDto: components.TeamCreationDto;
};

/**
 * Create team response
 */
export type ConsoleV1UsersControllerGenCreateTeamResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.TeamDto;
};

/** @internal */
export const ConsoleV1UsersControllerGenCreateTeamRequest$inboundSchema: z.ZodType<
    ConsoleV1UsersControllerGenCreateTeamRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-respect-review-settings": z.string().optional(),
        TeamCreationDto: components.TeamCreationDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            TeamCreationDto: "teamCreationDto",
        });
    });

/** @internal */
export type ConsoleV1UsersControllerGenCreateTeamRequest$Outbound = {
    "x-respect-review-settings"?: string | undefined;
    TeamCreationDto: components.TeamCreationDto$Outbound;
};

/** @internal */
export const ConsoleV1UsersControllerGenCreateTeamRequest$outboundSchema: z.ZodType<
    ConsoleV1UsersControllerGenCreateTeamRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1UsersControllerGenCreateTeamRequest
> = z
    .object({
        xRespectReviewSettings: z.string().optional(),
        teamCreationDto: components.TeamCreationDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            teamCreationDto: "TeamCreationDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1UsersControllerGenCreateTeamRequest$ {
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1UsersControllerGenCreateTeamRequest$inboundSchema;
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1UsersControllerGenCreateTeamRequest$outboundSchema;
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamRequest$Outbound` instead. */
    export type Outbound = ConsoleV1UsersControllerGenCreateTeamRequest$Outbound;
}

/** @internal */
export const ConsoleV1UsersControllerGenCreateTeamResponseBody$inboundSchema: z.ZodType<
    ConsoleV1UsersControllerGenCreateTeamResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.TeamDto$inboundSchema,
});

/** @internal */
export type ConsoleV1UsersControllerGenCreateTeamResponseBody$Outbound = {
    message: string;
    data: components.TeamDto$Outbound;
};

/** @internal */
export const ConsoleV1UsersControllerGenCreateTeamResponseBody$outboundSchema: z.ZodType<
    ConsoleV1UsersControllerGenCreateTeamResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1UsersControllerGenCreateTeamResponseBody
> = z.object({
    message: z.string(),
    data: components.TeamDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1UsersControllerGenCreateTeamResponseBody$ {
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1UsersControllerGenCreateTeamResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1UsersControllerGenCreateTeamResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1UsersControllerGenCreateTeamResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1UsersControllerGenCreateTeamResponseBody$Outbound;
}
