/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest = {
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    ingestionScheduleUpdateContractDto: components.IngestionScheduleUpdateContractDto;
};

/**
 * Update Ingestion Schedule Success
 */
export type ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.IngestionScheduleDto;
};

/** @internal */
export const ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$inboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-respect-review-settings": z.string().optional(),
        IngestionScheduleUpdateContractDto:
            components.IngestionScheduleUpdateContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            IngestionScheduleUpdateContractDto: "ingestionScheduleUpdateContractDto",
        });
    });

/** @internal */
export type ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$Outbound = {
    "x-respect-review-settings"?: string | undefined;
    IngestionScheduleUpdateContractDto: components.IngestionScheduleUpdateContractDto$Outbound;
};

/** @internal */
export const ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$outboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest
> = z
    .object({
        xRespectReviewSettings: z.string().optional(),
        ingestionScheduleUpdateContractDto:
            components.IngestionScheduleUpdateContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            ingestionScheduleUpdateContractDto: "IngestionScheduleUpdateContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$ {
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$inboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$outboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$Outbound` instead. */
    export type Outbound = ConsoleV1IngestionControllerGenUpdateIngestionScheduleRequest$Outbound;
}

/** @internal */
export const ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$inboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.IngestionScheduleDto$inboundSchema,
});

/** @internal */
export type ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$Outbound = {
    message: string;
    data: components.IngestionScheduleDto$Outbound;
};

/** @internal */
export const ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$outboundSchema: z.ZodType<
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody
> = z.object({
    message: z.string(),
    data: components.IngestionScheduleDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$ {
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$Outbound` instead. */
    export type Outbound =
        ConsoleV1IngestionControllerGenUpdateIngestionScheduleResponseBody$Outbound;
}
