/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1MetricValuesControllerGenListMetricValuesRequest = {
    date: string;
    metricName?: string | undefined;
    metricType?: string | undefined;
    /**
     * Results per page
     */
    limit?: any | undefined;
    /**
     * Page number
     */
    page?: any | undefined;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * List All Metric Values Response
 */
export type ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.MetricValueDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1MetricValuesControllerGenListMetricValuesRequest$inboundSchema: z.ZodType<
    ConsoleV1MetricValuesControllerGenListMetricValuesRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        date: z.string(),
        metricName: z.string().optional(),
        metricType: z.string().optional(),
        limit: z.any().optional(),
        page: z.any().optional(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1MetricValuesControllerGenListMetricValuesRequest$Outbound = {
    date: string;
    metricName?: string | undefined;
    metricType?: string | undefined;
    limit?: any | undefined;
    page?: any | undefined;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1MetricValuesControllerGenListMetricValuesRequest$outboundSchema: z.ZodType<
    ConsoleV1MetricValuesControllerGenListMetricValuesRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1MetricValuesControllerGenListMetricValuesRequest
> = z
    .object({
        date: z.string(),
        metricName: z.string().optional(),
        metricType: z.string().optional(),
        limit: z.any().optional(),
        page: z.any().optional(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1MetricValuesControllerGenListMetricValuesRequest$ {
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesRequest$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1MetricValuesControllerGenListMetricValuesRequest$inboundSchema;
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1MetricValuesControllerGenListMetricValuesRequest$outboundSchema;
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesRequest$Outbound` instead. */
    export type Outbound = ConsoleV1MetricValuesControllerGenListMetricValuesRequest$Outbound;
}

/** @internal */
export const ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$inboundSchema: z.ZodType<
    ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.MetricValueDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$Outbound = {
    message: string;
    data: Array<components.MetricValueDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$outboundSchema: z.ZodType<
    ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.MetricValueDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$ {
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1MetricValuesControllerGenListMetricValuesResponseBody$Outbound;
}
