/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1AutotunesControllerGenListRequest = {
    /**
     * Results per page
     */
    limit?: any | undefined;
    /**
     * Page number
     */
    page?: any | undefined;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Autotune Experiments listed successfully.
 */
export type ConsoleV1AutotunesControllerGenListResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.AutotuneExperimentDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1AutotunesControllerGenListRequest$inboundSchema: z.ZodType<
    ConsoleV1AutotunesControllerGenListRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1AutotunesControllerGenListRequest$Outbound = {
    limit?: any | undefined;
    page?: any | undefined;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1AutotunesControllerGenListRequest$outboundSchema: z.ZodType<
    ConsoleV1AutotunesControllerGenListRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1AutotunesControllerGenListRequest
> = z
    .object({
        limit: z.any().optional(),
        page: z.any().optional(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1AutotunesControllerGenListRequest$ {
    /** @deprecated use `ConsoleV1AutotunesControllerGenListRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1AutotunesControllerGenListRequest$inboundSchema;
    /** @deprecated use `ConsoleV1AutotunesControllerGenListRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1AutotunesControllerGenListRequest$outboundSchema;
    /** @deprecated use `ConsoleV1AutotunesControllerGenListRequest$Outbound` instead. */
    export type Outbound = ConsoleV1AutotunesControllerGenListRequest$Outbound;
}

/** @internal */
export const ConsoleV1AutotunesControllerGenListResponseBody$inboundSchema: z.ZodType<
    ConsoleV1AutotunesControllerGenListResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.AutotuneExperimentDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1AutotunesControllerGenListResponseBody$Outbound = {
    message: string;
    data: Array<components.AutotuneExperimentDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1AutotunesControllerGenListResponseBody$outboundSchema: z.ZodType<
    ConsoleV1AutotunesControllerGenListResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1AutotunesControllerGenListResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.AutotuneExperimentDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1AutotunesControllerGenListResponseBody$ {
    /** @deprecated use `ConsoleV1AutotunesControllerGenListResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1AutotunesControllerGenListResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1AutotunesControllerGenListResponseBody$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1AutotunesControllerGenListResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1AutotunesControllerGenListResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1AutotunesControllerGenListResponseBody$Outbound;
}
