/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1HoldoutsControllerGenPartialUpdateRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    holdoutPartialUpdateContractDto: components.HoldoutPartialUpdateContractDto;
};

/**
 * Update holdout response
 */
export type ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.HoldoutDto;
};

/** @internal */
export const ConsoleV1HoldoutsControllerGenPartialUpdateRequest$inboundSchema: z.ZodType<
    ConsoleV1HoldoutsControllerGenPartialUpdateRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        HoldoutPartialUpdateContractDto: components.HoldoutPartialUpdateContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            HoldoutPartialUpdateContractDto: "holdoutPartialUpdateContractDto",
        });
    });

/** @internal */
export type ConsoleV1HoldoutsControllerGenPartialUpdateRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    HoldoutPartialUpdateContractDto: components.HoldoutPartialUpdateContractDto$Outbound;
};

/** @internal */
export const ConsoleV1HoldoutsControllerGenPartialUpdateRequest$outboundSchema: z.ZodType<
    ConsoleV1HoldoutsControllerGenPartialUpdateRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1HoldoutsControllerGenPartialUpdateRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        holdoutPartialUpdateContractDto: components.HoldoutPartialUpdateContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            holdoutPartialUpdateContractDto: "HoldoutPartialUpdateContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1HoldoutsControllerGenPartialUpdateRequest$ {
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1HoldoutsControllerGenPartialUpdateRequest$inboundSchema;
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1HoldoutsControllerGenPartialUpdateRequest$outboundSchema;
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateRequest$Outbound` instead. */
    export type Outbound = ConsoleV1HoldoutsControllerGenPartialUpdateRequest$Outbound;
}

/** @internal */
export const ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$inboundSchema: z.ZodType<
    ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.HoldoutDto$inboundSchema,
});

/** @internal */
export type ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$Outbound = {
    message: string;
    data: components.HoldoutDto$Outbound;
};

/** @internal */
export const ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$outboundSchema: z.ZodType<
    ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody
> = z.object({
    message: z.string(),
    data: components.HoldoutDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$ {
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1HoldoutsControllerGenPartialUpdateResponseBody$Outbound;
}
