/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1DynamicConfigControllerGenListRequest = {
    /**
     * Name of the creator.
     */
    creatorName?: string | null | undefined;
    /**
     * ID of the user who created the entity.
     */
    creatorID?: string | null | undefined;
    /**
     * Filter by tags
     */
    tags?: any | undefined;
    /**
     * Results per page
     */
    limit?: any | undefined;
    /**
     * Page number
     */
    page?: any | undefined;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * List Dynamic Configs Success
 */
export type ConsoleV1DynamicConfigControllerGenListResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: Array<components.DynamicConfigDto>;
    /**
     * Pagination metadata for checking if there is next page for example.
     */
    pagination: components.PaginationResponseMetadataDto;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenListRequest$inboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenListRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        creatorName: z.nullable(z.string()).optional(),
        creatorID: z.nullable(z.string()).optional(),
        tags: z.any().optional(),
        limit: z.any().optional(),
        page: z.any().optional(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1DynamicConfigControllerGenListRequest$Outbound = {
    creatorName?: string | null | undefined;
    creatorID?: string | null | undefined;
    tags?: any | undefined;
    limit?: any | undefined;
    page?: any | undefined;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenListRequest$outboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenListRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1DynamicConfigControllerGenListRequest
> = z
    .object({
        creatorName: z.nullable(z.string()).optional(),
        creatorID: z.nullable(z.string()).optional(),
        tags: z.any().optional(),
        limit: z.any().optional(),
        page: z.any().optional(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1DynamicConfigControllerGenListRequest$ {
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1DynamicConfigControllerGenListRequest$inboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1DynamicConfigControllerGenListRequest$outboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListRequest$Outbound` instead. */
    export type Outbound = ConsoleV1DynamicConfigControllerGenListRequest$Outbound;
}

/** @internal */
export const ConsoleV1DynamicConfigControllerGenListResponseBody$inboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenListResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: z.array(components.DynamicConfigDto$inboundSchema),
    pagination: components.PaginationResponseMetadataDto$inboundSchema,
});

/** @internal */
export type ConsoleV1DynamicConfigControllerGenListResponseBody$Outbound = {
    message: string;
    data: Array<components.DynamicConfigDto$Outbound>;
    pagination: components.PaginationResponseMetadataDto$Outbound;
};

/** @internal */
export const ConsoleV1DynamicConfigControllerGenListResponseBody$outboundSchema: z.ZodType<
    ConsoleV1DynamicConfigControllerGenListResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1DynamicConfigControllerGenListResponseBody
> = z.object({
    message: z.string(),
    data: z.array(components.DynamicConfigDto$outboundSchema),
    pagination: components.PaginationResponseMetadataDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1DynamicConfigControllerGenListResponseBody$ {
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListResponseBody$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1DynamicConfigControllerGenListResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1DynamicConfigControllerGenListResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1DynamicConfigControllerGenListResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1DynamicConfigControllerGenListResponseBody$Outbound;
}
