/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1HoldoutOverridesControllerGenAddRequest = {
    /**
     * id
     */
    id: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    updateOverridesContractDto: components.UpdateOverridesContractDto;
};

/**
 * Add Holdout Overrides Success
 */
export type ConsoleV1HoldoutOverridesControllerGenAddResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    /**
     * Contract for overrides
     */
    data: components.OverrideDto;
};

/** @internal */
export const ConsoleV1HoldoutOverridesControllerGenAddRequest$inboundSchema: z.ZodType<
    ConsoleV1HoldoutOverridesControllerGenAddRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "x-respect-review-settings": z.string().optional(),
        UpdateOverridesContractDto: components.UpdateOverridesContractDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            UpdateOverridesContractDto: "updateOverridesContractDto",
        });
    });

/** @internal */
export type ConsoleV1HoldoutOverridesControllerGenAddRequest$Outbound = {
    id: string;
    "x-respect-review-settings"?: string | undefined;
    UpdateOverridesContractDto: components.UpdateOverridesContractDto$Outbound;
};

/** @internal */
export const ConsoleV1HoldoutOverridesControllerGenAddRequest$outboundSchema: z.ZodType<
    ConsoleV1HoldoutOverridesControllerGenAddRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1HoldoutOverridesControllerGenAddRequest
> = z
    .object({
        id: z.string(),
        xRespectReviewSettings: z.string().optional(),
        updateOverridesContractDto: components.UpdateOverridesContractDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            updateOverridesContractDto: "UpdateOverridesContractDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1HoldoutOverridesControllerGenAddRequest$ {
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddRequest$inboundSchema` instead. */
    export const inboundSchema = ConsoleV1HoldoutOverridesControllerGenAddRequest$inboundSchema;
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddRequest$outboundSchema` instead. */
    export const outboundSchema = ConsoleV1HoldoutOverridesControllerGenAddRequest$outboundSchema;
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddRequest$Outbound` instead. */
    export type Outbound = ConsoleV1HoldoutOverridesControllerGenAddRequest$Outbound;
}

/** @internal */
export const ConsoleV1HoldoutOverridesControllerGenAddResponseBody$inboundSchema: z.ZodType<
    ConsoleV1HoldoutOverridesControllerGenAddResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.OverrideDto$inboundSchema,
});

/** @internal */
export type ConsoleV1HoldoutOverridesControllerGenAddResponseBody$Outbound = {
    message: string;
    data: components.OverrideDto$Outbound;
};

/** @internal */
export const ConsoleV1HoldoutOverridesControllerGenAddResponseBody$outboundSchema: z.ZodType<
    ConsoleV1HoldoutOverridesControllerGenAddResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1HoldoutOverridesControllerGenAddResponseBody
> = z.object({
    message: z.string(),
    data: components.OverrideDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1HoldoutOverridesControllerGenAddResponseBody$ {
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1HoldoutOverridesControllerGenAddResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1HoldoutOverridesControllerGenAddResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1HoldoutOverridesControllerGenAddResponseBody$Outbound` instead. */
    export type Outbound = ConsoleV1HoldoutOverridesControllerGenAddResponseBody$Outbound;
}
