/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest = {
    /**
     * name
     */
    name: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
};

/**
 * Delete Entity Property Source response
 */
export type ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody = {
    message?: string | undefined;
};

/** @internal */
export const ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$inboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        name: z.string(),
        "x-respect-review-settings": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
        });
    });

/** @internal */
export type ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$Outbound = {
    name: string;
    "x-respect-review-settings"?: string | undefined;
};

/** @internal */
export const ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$outboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest
> = z
    .object({
        name: z.string(),
        xRespectReviewSettings: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$ {
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$Outbound` instead. */
    export type Outbound =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceRequest$Outbound;
}

/** @internal */
export const ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$inboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
});

/** @internal */
export type ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$Outbound = {
    message?: string | undefined;
};

/** @internal */
export const ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$outboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody
> = z.object({
    message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$ {
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$Outbound` instead. */
    export type Outbound =
        ConsoleV1ExperimentsControllerGenRemoveEntityPropertySourceResponseBody$Outbound;
}
