/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest = {
    /**
     * name
     */
    name: string;
    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    xRespectReviewSettings?: string | undefined;
    entityPropertySourceQueryUpdateDto: components.EntityPropertySourceQueryUpdateDto;
};

/**
 * Post Entity Property Source response
 */
export type ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody = {
    /**
     * A simple string explaining the result of the operation.
     */
    message: string;
    data: components.EntityPropertySourceDto;
};

/** @internal */
export const ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$inboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        name: z.string(),
        "x-respect-review-settings": z.string().optional(),
        EntityPropertySourceQueryUpdateDto:
            components.EntityPropertySourceQueryUpdateDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "x-respect-review-settings": "xRespectReviewSettings",
            EntityPropertySourceQueryUpdateDto: "entityPropertySourceQueryUpdateDto",
        });
    });

/** @internal */
export type ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$Outbound = {
    name: string;
    "x-respect-review-settings"?: string | undefined;
    EntityPropertySourceQueryUpdateDto: components.EntityPropertySourceQueryUpdateDto$Outbound;
};

/** @internal */
export const ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$outboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest
> = z
    .object({
        name: z.string(),
        xRespectReviewSettings: z.string().optional(),
        entityPropertySourceQueryUpdateDto:
            components.EntityPropertySourceQueryUpdateDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xRespectReviewSettings: "x-respect-review-settings",
            entityPropertySourceQueryUpdateDto: "EntityPropertySourceQueryUpdateDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$ {
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$Outbound` instead. */
    export type Outbound =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryRequest$Outbound;
}

/** @internal */
export const ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$inboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
    data: components.EntityPropertySourceDto$inboundSchema,
});

/** @internal */
export type ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$Outbound =
    {
        message: string;
        data: components.EntityPropertySourceDto$Outbound;
    };

/** @internal */
export const ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$outboundSchema: z.ZodType<
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$Outbound,
    z.ZodTypeDef,
    ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody
> = z.object({
    message: z.string(),
    data: components.EntityPropertySourceDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$ {
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$inboundSchema` instead. */
    export const inboundSchema =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$inboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$outboundSchema` instead. */
    export const outboundSchema =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$outboundSchema;
    /** @deprecated use `ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$Outbound` instead. */
    export type Outbound =
        ConsoleV1ExperimentsControllerGenUpdateEntityPropertySourceQueryResponseBody$Outbound;
}
