/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const Refresh = {
    Full: "full",
    Incremental: "incremental",
    Metric: "metric",
    Power: "power",
} as const;
export type Refresh = ClosedEnum<typeof Refresh>;

export type EchidnaGateLoadPulseQueryDto = {
    refresh?: Refresh | undefined;
    ruleId: string;
    turboMode?: boolean | undefined;
};

/** @internal */
export const Refresh$inboundSchema: z.ZodNativeEnum<typeof Refresh> = z.nativeEnum(Refresh);

/** @internal */
export const Refresh$outboundSchema: z.ZodNativeEnum<typeof Refresh> = Refresh$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Refresh$ {
    /** @deprecated use `Refresh$inboundSchema` instead. */
    export const inboundSchema = Refresh$inboundSchema;
    /** @deprecated use `Refresh$outboundSchema` instead. */
    export const outboundSchema = Refresh$outboundSchema;
}

/** @internal */
export const EchidnaGateLoadPulseQueryDto$inboundSchema: z.ZodType<
    EchidnaGateLoadPulseQueryDto,
    z.ZodTypeDef,
    unknown
> = z.object({
    refresh: Refresh$inboundSchema.default("full"),
    ruleId: z.string(),
    turboMode: z.boolean().optional(),
});

/** @internal */
export type EchidnaGateLoadPulseQueryDto$Outbound = {
    refresh: string;
    ruleId: string;
    turboMode?: boolean | undefined;
};

/** @internal */
export const EchidnaGateLoadPulseQueryDto$outboundSchema: z.ZodType<
    EchidnaGateLoadPulseQueryDto$Outbound,
    z.ZodTypeDef,
    EchidnaGateLoadPulseQueryDto
> = z.object({
    refresh: Refresh$outboundSchema.default("full"),
    ruleId: z.string(),
    turboMode: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EchidnaGateLoadPulseQueryDto$ {
    /** @deprecated use `EchidnaGateLoadPulseQueryDto$inboundSchema` instead. */
    export const inboundSchema = EchidnaGateLoadPulseQueryDto$inboundSchema;
    /** @deprecated use `EchidnaGateLoadPulseQueryDto$outboundSchema` instead. */
    export const outboundSchema = EchidnaGateLoadPulseQueryDto$outboundSchema;
    /** @deprecated use `EchidnaGateLoadPulseQueryDto$Outbound` instead. */
    export type Outbound = EchidnaGateLoadPulseQueryDto$Outbound;
}
