/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PaginationResponseMetadataDto = {
    itemsPerPage: number;
    pageNumber: number;
    nextPage?: string | undefined;
    previousPage?: string | undefined;
    totalItems?: number | undefined;
    all?: string | undefined;
};

/** @internal */
export const PaginationResponseMetadataDto$inboundSchema: z.ZodType<
    PaginationResponseMetadataDto,
    z.ZodTypeDef,
    unknown
> = z.object({
    itemsPerPage: z.number(),
    pageNumber: z.number(),
    nextPage: z.string().optional(),
    previousPage: z.string().optional(),
    totalItems: z.number().optional(),
    all: z.string().optional(),
});

/** @internal */
export type PaginationResponseMetadataDto$Outbound = {
    itemsPerPage: number;
    pageNumber: number;
    nextPage?: string | undefined;
    previousPage?: string | undefined;
    totalItems?: number | undefined;
    all?: string | undefined;
};

/** @internal */
export const PaginationResponseMetadataDto$outboundSchema: z.ZodType<
    PaginationResponseMetadataDto$Outbound,
    z.ZodTypeDef,
    PaginationResponseMetadataDto
> = z.object({
    itemsPerPage: z.number(),
    pageNumber: z.number(),
    nextPage: z.string().optional(),
    previousPage: z.string().optional(),
    totalItems: z.number().optional(),
    all: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaginationResponseMetadataDto$ {
    /** @deprecated use `PaginationResponseMetadataDto$inboundSchema` instead. */
    export const inboundSchema = PaginationResponseMetadataDto$inboundSchema;
    /** @deprecated use `PaginationResponseMetadataDto$outboundSchema` instead. */
    export const outboundSchema = PaginationResponseMetadataDto$outboundSchema;
    /** @deprecated use `PaginationResponseMetadataDto$Outbound` instead. */
    export type Outbound = PaginationResponseMetadataDto$Outbound;
}
