/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SegmentIDListResetContractDto = {
    ids: Array<string>;
};

/** @internal */
export const SegmentIDListResetContractDto$inboundSchema: z.ZodType<
    SegmentIDListResetContractDto,
    z.ZodTypeDef,
    unknown
> = z.object({
    ids: z.array(z.string()),
});

/** @internal */
export type SegmentIDListResetContractDto$Outbound = {
    ids: Array<string>;
};

/** @internal */
export const SegmentIDListResetContractDto$outboundSchema: z.ZodType<
    SegmentIDListResetContractDto$Outbound,
    z.ZodTypeDef,
    SegmentIDListResetContractDto
> = z.object({
    ids: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SegmentIDListResetContractDto$ {
    /** @deprecated use `SegmentIDListResetContractDto$inboundSchema` instead. */
    export const inboundSchema = SegmentIDListResetContractDto$inboundSchema;
    /** @deprecated use `SegmentIDListResetContractDto$outboundSchema` instead. */
    export const outboundSchema = SegmentIDListResetContractDto$outboundSchema;
    /** @deprecated use `SegmentIDListResetContractDto$Outbound` instead. */
    export type Outbound = SegmentIDListResetContractDto$Outbound;
}
